### ISSUE TITLE
🚩 Design Decision: Keep features customizable

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#433]
### Is your feature request related to a problem? Please describe

One of the features we are highlighting in this app is that its `🎨 Customizable: Change everything to your needs.`

My last 2 feature requests (#431, #432) arose because we didn't adhere to this principle. The actions and imports couldn't be accessed from where I wanted as part of my workflow.

### Describe your feature request!

I propose making `🎨 Customizable: Change everything to your needs.` one of our core principles of design for this app. This is the principle behind modern great apps like vscode, Obsidian, sumatrapdf reader.

Which means all further features (actions, painters or whatever) should be customizable
- accessed from any where the user needs them (toolbar, menu, etc.) - Customizable UI
- accessed with their desired `keybindings` if keyboard is present - Customizable keybindings
- accessed with their desired `touch events & gestures` for screens with touch input
- accessed with their desired `stylus events & gestures` for devices with stylus/pen input

Best practices & industry standards should be the default behaviour but lets keep everything customizable

From the current 
- detaching actions/tools from keybindings 
- making these keybindings customizable
- implementing touch & pen gestures and binding them to these actions
so that  app is optimized for different screensizes (large, small) & different inputs (keyboard, mouse, touch, pen)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
```[tasklist]
### Tasks
- [ ] https://github.com/LinwoodDev/Butterfly/issues/431
- [ ] https://github.com/LinwoodDev/Butterfly/issues/432
```

**Comment by CodeDoctorDE** [comment]
You are correct. We should make everything customizable!
Keybindings are currently a bit difficult because flutter doesn't support customizing out of the box.
I will develop a plugin for butterfly to support this.
There are behavior settings in the app if you want to switch the painter with a right/middle click or with a different device. I think this point is completed.

**Comment by CodeDoctorDE** [comment]
Can we make a task list for these to track these here?
I would close this issue if we are finished!
I don't like opensource projects with thousand of issues that are very inactive. I want to have an overview over all issues

**Comment by CodeDoctorDE** [comment]
Butterfly 2.0.0-rc.0 was released.
Please create specific issues if you found anything missing in the app.
