### ISSUE TITLE
☂️Keyboard shortcuts in Butterfly

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#439]
### Describe your feature request!

umbrella issue for all keyboard shortcuts related

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
```[tasklist]
### Tasks
- [ ] https://github.com/LinwoodDev/Butterfly/issues/436
- [ ] https://github.com/LinwoodDev/Butterfly/issues/435
```

**Comment by CodeDoctorDE** [comment]
I will close this issue when 2.0 is released.
Feel free to link shortcuts issues here.

**Comment by CodeDoctorDE** [comment]
Butterfly 2.0.0-rc.0 was released.
Please create specific issues if you found anything missing in the app.
